name: 'Close Issue Message'
description: 'A simple action to post a message under an issue that is about to be closed'
inputs:
  repo-token:
    description: 'Token for the repository. Can be passed in using {{ secrets.GITHUB_TOKEN }}'
    required: true
  message:
    description: 'The message you want to be commented whenever an issue is closed'
    required: true
runs:
  using: "composite"
  steps:
    - name: Comment on issue
      run: |
        echo "${{ inputs.message }}" > message.md
        gh issue comment ${{ github.event.issue.number }} --body "$(cat message.md)"
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.repo-token }}
        OWNER: ${{ github.repository_owner }}
        REPO: ${{ github.event.repository.name }}